R120

diff --git a/bootstat/bootstat_summary b/bootstat/bootstat_summary
--- a/bootstat/bootstat_summary
+++ b/bootstat/bootstat_summary
@@ -1,17 +1,22 @@
 #!/bin/sh
-# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
+# Copyright 2012 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+# This isn't the exact copy that will be used in production, but it's better
+# than pointing shellcheck at /dev/null.
+# shellcheck source=../../scripts/lib/shflags/shflags
 . /usr/share/misc/shflags || exit 1
 
-DEFINE_string directory /tmp "Bootstat archive directory" d
+DEFINE_string directory /run/bootstat "Bootstat archive directory" d
 
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
-readonly NCPU="$(grep -c '^processor' /proc/cpuinfo)"
+NCPU="$(grep -c '^processor' /proc/cpuinfo)"
+readonly NCPU
 
+# shellcheck disable=SC2016 # We want a literal awk script.
 SUMMARIZE_TIME='
   BEGIN {
     printf "%8s %4s %8s %4s  %s\n", "time", "%cpu", "dt", "%dt", "event"
@@ -38,20 +43,35 @@ SUMMARIZE_TIME='
 
 # If there are no arguments on the command line, summarize all the
 # events.  If there are arguments, summarize only the named events.
-# Error checking is deliberately minimal, to keep this script simple.
 if [ $# -eq 0 ]; then
-  EVENTS="$(ls "${FLAGS_directory}/uptime-"*)"
+  set -- "${FLAGS_directory}/uptime-"*
 else
-  for EV in "$@"; do
-    EVENTS="${EVENTS} ${FLAGS_directory}/uptime-${EV}"
+  max=$#
+  i=0
+  while [ $((i += 1)) -le "${max}" ]; do
+    set -- "$@" "${FLAGS_directory}/uptime-$1"
+    shift
   done
 fi
+
+max=$#
+i=0
+# Catch some basic errors so awk doesn't choke.
+while [ $((i += 1)) -le "${max}" ]; do
+  if [ -r "$1" ]; then
+    set -- "$@" "$1"
+  else
+    echo "Error: file $1 is not readable" 1>&2
+  fi
+  shift
+done
 
 # Pipeline explained:
 #  1st awk program: print times as milliseconds and normalize idle time
 #     by NCPU.
 #  sort: sort the events by the uptime timestamp.
-#  sed: remove '/tmp/uptime-' from the event name.
+#  sed: remove '/run/bootstat/uptime-' from the event name.
 #  2nd awk program:  produce the summarized output
-awk '{print 1000*$1, 1000*$2/'${NCPU}', FILENAME}' ${EVENTS} |
+awk 'BEGIN{OFMT="%f"}
+     {print 1000*$1, 1000*$2/'"${NCPU}"', FILENAME}' "$@" |
   sort -k 1n | sed 's=[^ ]*uptime-==' | awk "${SUMMARIZE_TIME}"
diff --git a/crosh/network_diag b/crosh/network_diag
--- a/crosh/network_diag
+++ b/crosh/network_diag
@@ -1,53 +1,71 @@
 #!/bin/bash
 
-# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
+# Copyright 2010 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
-IFCONFIG=/bin/ifconfig
-LSUSB=/usr/sbin/lsusb
-LSPCI=/usr/sbin/lspci
-IW=/usr/sbin/iw
-ARP=/sbin/arp
-ARPING=/sbin/arping
-TLSDATE=/usr/bin/tlsdate
-ETHTOOL=/usr/sbin/ethtool
+echo "$0: This command is deprecated." >&2
+echo "$0: Please see https://issuetracker.google.com/267537630" >&2
+exit 1
+
+# Use $PATH lookup for tools.  Add sbin in case script is run by non-root.
+PATH+=:/sbin:/usr/sbin
+
+IFCONFIG=ifconfig
+LSUSB=lsusb
+LSPCI=lspci
+IW=iw
+ARP=arp
+ARPING=arping
+TLSDATE=tlsdate
+ETHTOOL=ethtool
 anonymize_output="${ANONYMIZE_OUTPUT-no}"
 fail_count=0
 CROS_CERTS=/usr/share/chromeos-ca-certificates/
 declare -A fn_entry
 
-# Annotate function entry.
-fn_enter () {
+# Annotate function entry.  Function name is provided by caller.
+_fn_enter() {
   local fn="$1"
   fn_entry["${fn}"]=1
-  echo "Entering $*"
+  echo "### Entering $*"
 }
 
-# Annotate function entry.  Also, return non-zero if function has
-# been called more than once
-fn_enter_once () {
+# Annotate function entry.  Function name is automatically the parent.
+fn_enter() {
+  _fn_enter "${FUNCNAME[1]}" "$@"
+}
+
+# Annotate function entry.  Function name is provided by caller.
+# Also, return non-zero if function has been called more than once.
+_fn_enter_once() {
   local fn="$1"
   [ -n "${fn_entry["${fn}"]}" ] && return 1
-  fn_enter "$@"
+  _fn_enter "$@"
+}
+
+# Annotate function entry.  Function name is automatically the parent.
+# Also, return non-zero if function has been called more than once.
+fn_enter_once() {
+  _fn_enter_once "${FUNCNAME[1]}" "$@"
 }
 
 # Output pass/fail reports
-pass () {
-    echo "PASS: $*"
+pass() {
+  echo "PASS: $*"
 }
-fail () {
-    echo "FAIL: $*"
-    fail_count="$((fail_count+1))"
+fail() {
+  echo "FAIL: $*"
+  fail_count="$((fail_count+1))"
 }
 
 # Split a dotted decimal string
-do_address_parts () {
+do_address_parts() {
   (IFS=" ."; echo $1)
 }
 
 # Perform a mask (binary "&") between two dotted-decimal strings
-do_netmask () {
+do_netmask() {
   local -a ip=($(do_address_parts "$1"))
   local -a mask=($(do_address_parts "$2"))
   local -a ret
@@ -61,7 +79,7 @@ do_netmask () {
 # @ip: Destination IP address
 # @route_flags: Search for this value in the "Flags" column
 # @part: Column from the netstat output to return
-get_route () {
+get_route() {
   local ip="$1"
   local route_flags="$2"
   shift ; shift
@@ -79,17 +97,17 @@ get_route () {
 }
 
 # Return the interface through which traffic to given neigbor IP should go
-get_if_route () {
+get_if_route() {
   get_route "$1" U 7
 }
 
 # Return the gateway IP to which traffic to given remote IP should be forwarded
-get_gw_route () {
+get_gw_route() {
   get_route "$1" UG 1 7
 }
 
 # Trace down a symbolic link until we reach a dead-end (or a real file)
-get_tracelink () {
+get_tracelink() {
   local file="$1"
   local link_count=0
   while [ -h "${file}" -o -e "${file}" ] ; do
@@ -107,30 +125,30 @@ get_tracelink () {
 }
 
 # Return the IP addresses of the currently configured nameservers
-get_nameservers () {
+get_nameservers() {
   awk '/^nameserver/ {print $2}' /etc/resolv.conf
 }
 
 # Return list of interface names
-get_iflist () {
+get_iflist() {
   ls /sys/class/net/ | egrep -v '^(lo|sit)'
 }
 
 # Return IP address of a given network interface
-get_if_addr () {
+get_if_addr() {
   ifc="$1"
   ${IFCONFIG} "${ifc}" | grep "inet addr" | sed  -e 's/.*addr://; s/ .*//'
 }
 
 # Super-gross method for looking up IP address of a given hostname
-get_host_addr () {
+get_host_addr() {
   # TODO(pstew): super gross -- but there's no host/dig/nslookup/dnsquery
   local host="$1"
   ping -c1 "${host}" | head -1 | awk -v FS='[()]' '{print $2}'
 }
 
 # Find a the device name of a device given the driver's name
-get_class_driver () {
+get_class_driver() {
   local find_pat="$1"
   local find_driver="$2"
   for device in "/sys/class/${find_pat}"*; do
@@ -143,8 +161,9 @@ get_class_driver () {
 }
 
 # The "status" command can't be run as non-root, so we fake it here
-get_status () {
-  pid="$(pgrep $1)"
+get_status() {
+  local pid
+  pid="$(pgrep "$1")"
   if [ -n "${pid}" ] ; then
     pass "$1 is running, pid ${pid}"
     return 0
@@ -155,14 +174,14 @@ get_status () {
 }
 
 # Join the rest of the arguments using the first argument as a delimiter.
-join () {
+join() {
   local delim="$1"
   shift
   echo $(IFS="${delim}"; echo "$*")
 }
 
 # Compose a string from hex characters.
-hex_to_string () {
+hex_to_string() {
   local hex
   for hex in "$@"; do
     printf "\x${hex}"
@@ -170,7 +189,7 @@ hex_to_string () {
   printf "\n"
 }
 
-seconds_compare () {
+seconds_compare() {
   local test_time="$1"
   local reference_time="$2"
   if [ "${test_time}" -gt "${reference_time}" ] ; then
@@ -181,14 +200,14 @@ seconds_compare () {
 }
 
 # Read a DHCPCD lease file
-read_dhcp_lease () {
+read_dhcp_lease() {
   local file="$1"
   local message_types=(UNKNOWN DISCOVER OFFER REQUEST DECLINE \
                        ACK NACK RELEASE INFORM)
   local now="$(date +%s)"
   local lease_start="$(stat -c %Y "${file}")"
   local lease_age="$((now-lease_start))"
-  echo "  Lease file age: $lease_age"
+  echo "  Lease file age: ${lease_age}"
   local lease_int=($(od --address-radix=n --format=u1 \
                          --output-duplicates "${file}"))
   local lease_hex=($(od --address-radix=n --format=x1 \
@@ -207,10 +226,10 @@ read_dhcp_lease () {
   while [ -n "${lease_int[$idx]}" -a -n "${lease_int[$((idx+1))]}" ] ; do
     local opt="${lease_int[$idx]}"
     local len="${lease_int[$((idx+1))]}"
-    local data_int=(${lease_int[*]:$((idx+2)):$len})
-    local data_hex=(${lease_hex[*]:$((idx+2)):$len})
+    local data_int=(${lease_int[*]:$((idx+2)):${len}})
+    local data_hex=(${lease_hex[*]:$((idx+2)):${len}})
     idx="$((idx + 2 + len))"
-    case $opt in
+    case "${opt}" in
       0)
         break
         ;;
@@ -232,7 +251,8 @@ read_dhcp_lease () {
         ;;
       51)
         local lease_time="$(printf "%d"  0x$(join '' "${data_hex[@]}"))"
-        local lease_time_comment="$(seconds_compare "$lease_time" "$lease_age")"
+        local lease_time_comment="$(seconds_compare \
+                                    "${lease_time}" "${lease_age}")"
         echo "  Lease Time: ${lease_time} seconds (${lease_time_comment})"
         ;;
       53)
@@ -240,21 +260,22 @@ read_dhcp_lease () {
         ;;
       58)
         local renew_time="$(printf "%d"  0x$(join '' "${data_hex[@]}"))"
-        local renew_time_comment="$(seconds_compare "$renew_time" "$lease_age")"
-        echo "  Renew Time: $renew_time seconds (${renew_time_comment})"
+        local renew_time_comment="$(seconds_compare \
+                                    "${renew_time}" "${lease_age}")"
+        echo "  Renew Time: ${renew_time} seconds (${renew_time_comment})"
         ;;
       59)
         local rebind_time="$(printf "%d"  0x$(join '' "${data_hex[@]}"))"
         local rebind_time_comment="$(seconds_compare \
-                                     "$rebind_time" "$lease_age")"
-        echo "  Rebinding Time: $rebind_time seconds (${rebind_time_comment})"
+                                     "${rebind_time}" "${lease_age}")"
+        echo "  Rebinding Time: ${rebind_time} seconds (${rebind_time_comment})"
         ;;
     esac
   done
 }
 
 # Anonymize PII (except MAC addresses) so they are not transmitted.
-output_anonymize () {
+output_anonymize() {
   if [ "${anonymize_output}" != "yes" ]; then
     cat
     return
@@ -269,7 +290,7 @@ output_anonymize () {
 }
 
 # Read the logs
-tail_logs () {
+tail_logs() {
   files="$(for f in /var/log/messages{.2,.1,} ; do
     [ -f "${f}" ] && echo "${f}";
     done)"
@@ -281,8 +302,8 @@ tail_logs () {
 }
 
 # List all ethernet devices and their unique manufacturer strings
-get_device_list () {
-  fn_enter_once "${FUNCNAME}" || return
+get_device_list() {
+  fn_enter_once || return
   echo "Device list:"
   for ifc in $(get_iflist); do
     dir="$(readlink -f "/sys/class/net/${ifc}/device")"
@@ -303,18 +324,18 @@ get_device_list () {
 }
 
 # List all USB and PCI devices
-diag_devs () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_devs() {
+  fn_enter_once || return
   ${LSUSB}
   ${LSPCI}
 }
 
 # Check whether we are in sync with the time server
-diag_date () {
+diag_date() {
   local host="$1"
   local proxy="$2"
   local cmd=()
-  fn_enter "${FUNCNAME}" "$@"
+  fn_enter "$@"
   echo "Local time of day: $(date)"
   cmd=( "${TLSDATE}" -nv -H "${host}" )
   if [[ -n "${proxy}" ]]; then
@@ -322,7 +343,7 @@ diag_date () {
   fi
   date_out="$( "${cmd[@]}" 2>&1 >/dev/null )"
   date_exit="$?"
-  offset="$(echo "$date_out" | grep 'difference is' | cut -f8 -d' ')"
+  offset="$(echo "${date_out}" | grep 'difference is' | cut -f8 -d' ')"
   if [ "${date_exit}" != 0 ]; then
     fail "Unable to get date via tlsdate from ${host}: ${date_out}"
   elif [ "${offset}" = 0 ] ; then
@@ -335,8 +356,8 @@ diag_date () {
 }
 
 # Try to detect IP address collisions
-diag_ip_collision () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_ip_collision() {
+  fn_enter "$@"
   local ifc="$1"
   ip="$(get_if_addr "${ifc}")"
   if [ -z "${ip}" ]; then
@@ -351,8 +372,8 @@ diag_ip_collision () {
 }
 
 # Make sure we have an ARP table entry for $ip through $ifc
-diag_arp () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_arp() {
+  fn_enter "$@"
   local ip="$1"
   local ifc="$2"
   local failures=0
@@ -374,12 +395,12 @@ diag_arp () {
     fi
   fi
 
-  fn_enter_once "${FUNCNAME}_table" && "${ARP}" -an | output_anonymize
+  _fn_enter_once "${FUNCNAME[0]}_table" && "${ARP}" -an | output_anonymize
 
   return "${failures}"
 }
 
-show_routes () {
+show_routes() {
   netstat -nr
   echo "Raw routing tables:"
   cat /proc/net/route
@@ -387,8 +408,8 @@ show_routes () {
 }
 
 # Make sure we have a route to each host
-diag_route () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_route() {
+  fn_enter "$@"
   local failures=0
   for ip in "$@"; do
     ifinfo="$(get_if_route "${ip}")"
@@ -403,14 +424,14 @@ diag_route () {
     fi
   done
 
-  fn_enter_once "${FUNCNAME}_table" && show_routes
+  _fn_enter_once "${FUNCNAME[0]}_table" && show_routes
 
   return "${failures}"
 }
 
 # Figure whether we have IP connectivity to each host
-diag_ping () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_ping() {
+  fn_enter "$@"
   local failures=0
   for ip in "$@"; do
     if ping -c 3 "${ip}" | grep -q '0 received'; then
@@ -436,8 +457,8 @@ diag_ping () {
 }
 
 # Report the last DHCP interaction for a given network interface
-diag_dhcp () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_dhcp() {
+  fn_enter_once || return
   local ifc="$1"
   shift
 
@@ -461,8 +482,8 @@ diag_dhcp () {
 }
 
 # Perform diagnostics on an 802.11 interface
-diag_link_wifi () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_link_wifi() {
+  fn_enter "$@"
   ifc="$1"
 
   echo "wifi stats (all interfaces):"
@@ -498,8 +519,8 @@ diag_link_wifi () {
 }
 
 # Print out WiFi debugging info
-diag_wifi () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_wifi() {
+  fn_enter_once || return
 
   # Call out to debugd (which in turn calls this script's diag_wifi_internal
   # function with the debugd privileges needed to read debugfs contents).
@@ -513,14 +534,14 @@ diag_wifi () {
         /org/chromium/debugd org.chromium.debugd.GetLog "string:${log_name}"
 }
 
-diag_wifi_internal () {
+diag_wifi_internal() {
   local ifc
   for ifc in $(get_iflist); do
     if is_wifi "${ifc}" ; then
       echo "iw dev ${ifc} survey dump:"
       "${IW}" dev "${ifc}" survey dump | output_anonymize
-      echo "iw dev ${ifc} station dump:"
-      "${IW}" dev "${ifc}" station dump | output_anonymize
+      echo "iw dev ${ifc} station dump -v:"
+      "${IW}" dev "${ifc}" station dump -v | output_anonymize
       echo "iw dev ${ifc} scan dump:"
       "${IW}" dev "${ifc}" scan dump | output_anonymize | grep -v SSID
       echo "iw dev ${ifc} link:"
@@ -532,8 +553,8 @@ diag_wifi_internal () {
 }
 
 # Perform diagnostics on a WAN interface
-diag_link_cellular () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_link_cellular() {
+  fn_enter "$@"
   diag_cellular_dbus
   diag_devs
   qcdev="$(get_class_driver tty/ttyUSB qcserial)"
@@ -543,8 +564,8 @@ diag_link_cellular () {
   tail_logs | grep "QDL unable" | tail -3
 }
 
-diag_link_wired () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_link_wired() {
+  fn_enter "$@"
   local ifc="$1"
 
   echo "Output from ethtool ${ifc}:"
@@ -555,7 +576,7 @@ diag_link_wired () {
 
 # Tests to check to see if this is a modem.  Very abstract adaptation
 # from flimflam's tests
-is_modem () {
+is_modem() {
   local ifc="$1"
   driver="$(basename "$(readlink "/sys/class/net/${ifc}/device/driver")")"
   # Allow certain device types.
@@ -571,7 +592,7 @@ is_modem () {
   return 1
 }
 
-is_wifi () {
+is_wifi() {
   local ifc="$1"
   if expr "${ifc}" : wlan > /dev/null || \
      [ -e "/sys/class/net/${ifc}/phy80211" ] ; then
@@ -581,8 +602,8 @@ is_wifi () {
 }
 
 # Perform type-specific link diagnostics on a network interface
-diag_link () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_link() {
+  fn_enter "$@"
   ifc="$1"
 
   if [ "$(cat "/sys/class/net/${ifc}/carrier")" -eq 1 ]; then
@@ -603,16 +624,16 @@ diag_link () {
   tail_logs | grep "kernel:.*${ifc}" | tail -10
 }
 
-diag_linkall () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_linkall() {
+  fn_enter_once || return
   for ifc in $(get_iflist); do
     diag_link "${ifc}"
   done
 }
 
 # Perform generic diagnostics on a network interface
-diag_if () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_if() {
+  fn_enter "$@"
   ifc="$1"
   config="$("${IFCONFIG}" "${ifc}")"
   ret=0
@@ -639,8 +660,8 @@ diag_if () {
 
 # Query interface status on all network interfaces, and return an error if
 # none of them appear to be up
-diag_ifall () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_ifall() {
+  fn_enter_once || return
 
   local good_ifs=0
   for ifc in $(get_iflist); do
@@ -657,8 +678,8 @@ diag_ifall () {
 }
 
 # Diagnose nameserver connectivity
-diag_nameservers () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_nameservers() {
+  fn_enter_once || return
   nameservers="$(get_nameservers)"
   if [ -z "${nameservers}" ] ; then
     fail "No nameservers -- this is either a network failure or net misconfig"
@@ -675,10 +696,10 @@ diag_nameservers () {
 }
 
 # See if we can connect to a given host
-diag_connectivity () {
-  fn_enter_once "${FUNCNAME}" "$@" || exit 0
+diag_connectivity() {
+  fn_enter_once "$@" || exit 0
   local host="$1"
-  local ip="$(get_host_addr "$host")"
+  local ip="$(get_host_addr "${host}")"
   if [ -z "${ip}" ] ; then
     fail "Could not lookup host ${host}"
     diag_route
@@ -694,7 +715,7 @@ diag_connectivity () {
 }
 
 # Get information from flimflam about its state over D-Bus.
-dbus_get_object_properties () {
+dbus_get_object_properties() {
   local entity="$1"
   local object_type="$2"
   local object_path="${3-/}"
@@ -702,7 +723,7 @@ dbus_get_object_properties () {
     "${object_path}" "${entity}.${object_type}.GetProperties"
 }
 
-dbus_get_object_list () {
+dbus_get_object_list() {
   local entity="$1"
   local parent="$2"
   local child="$3"
@@ -719,8 +740,8 @@ dbus_get_object_list () {
     awk -v re="^/[0-9]+/${child}[/ ]" 'match($0, re) { print $2 }'
 }
 
-diag_flimflam_dbus () {
-  fn_enter_once "${FUNCNAME}" "$@"
+diag_flimflam_dbus() {
+  fn_enter_once "$@"
   local ff="org.chromium.flimflam"
   if [ -z "$1" ] ; then
     echo "Flimflam Manager:"
@@ -747,8 +768,8 @@ diag_flimflam_dbus () {
 }
 
 # Get information from ModemManager about its state over D-Bus
-diag_cellular_dbus () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_cellular_dbus() {
+  fn_enter "$@"
   dbus-send --fixed --system --print-reply --dest=org.chromium.ModemManager \
     /org/chromium/ModemManager \
     org.freedesktop.ModemManager.EnumerateDevices || \
@@ -756,8 +777,8 @@ diag_cellular_dbus () {
 }
 
 # Read lease information
-diag_dhcp_lease () {
-  fn_enter "${FUNCNAME}" "$@"
+diag_dhcp_lease() {
+  fn_enter "$@"
   local lease_dir=/var/lib/dhcpcd
   for file in "${lease_dir}/"*.lease; do
     echo "DHCP Lease file ${file}"
@@ -766,8 +787,8 @@ diag_dhcp_lease () {
 }
 
 # Probe process status of flimflam and its process descendants
-diag_flimflam () {
-  fn_enter_once "${FUNCNAME}" || return
+diag_flimflam() {
+  fn_enter_once || return
   local status="$(get_status shill)"
   echo "${status}"
   if ! echo "${status}" | fgrep -q 'running'; then
@@ -795,7 +816,7 @@ run_hosts_webget() {
 }
 
 # Try to connect to a host via SSL, diagnose failures.
-diag_hosts () {
+diag_hosts() {
   local host
   local proxy="$1"
   # Hosts is pulled from
@@ -866,7 +887,7 @@ diag_hosts () {
   done
 }
 
-run_webget () {
+run_webget() {
   local url="$1"
   local proxy="$2"
   local cmd=()
@@ -880,7 +901,7 @@ run_webget () {
 }
 
 # Try to connect to a host via SSL, diagnose failures
-diag_webget () {
+diag_webget() {
   local host="$1"
   local url="https://${host}"
   local proxy="$2"
@@ -931,24 +952,24 @@ diag_webget () {
       get_device_list
       diag_flimflam
   fi
-  return "$err"
+  return "${err}"
 }
 
 # Do standard run of tests
-diag_run () {
+diag_run() {
   local host="$1"
   local proxy="$2"
   if run_webget "https://${host}" "${proxy}"; then
-    pass "Loaded $host via HTTPS"
+    pass "Loaded ${host} via HTTPS"
   elif run_webget "http://${host}" "${proxy}"; then
-    pass "Loaded $host via HTTP (ignore any tlsdate failure below)"
+    pass "Loaded ${host} via HTTP (ignore any tlsdate failure below)"
   else
     diag_webget "${host}" "${proxy}"
   fi
   diag_date "${host}" "${proxy}"
 }
 
-valid_host () {
+valid_host() {
   local host="$1"
 
   # Allow things that look like valid IPv4/IPv6/DNS.  This doesn't deal with
@@ -959,7 +980,7 @@ valid_host () {
   [ "${host}" = "$(printf '%s' "${host}" | tr -cd 'A-Za-z0-9.:-')" ]
 }
 
-usage () {
+usage() {
   echo "Usage: $0 [--date|--flimflam|--link|--wifi|--help] [host]"
   echo "    --date:      Diagnose time-of-day"
   echo "                 ([host] must support SSL)"
@@ -977,7 +998,7 @@ usage () {
                          "(default: clients3.google.com)"
 }
 
-check_no_arg () {
+check_no_arg() {
   if [[ "$2" == "yes" ]]; then
     echo "Option $1 does not take any arguments"
     usage
@@ -985,7 +1006,7 @@ check_no_arg () {
   fi
 }
 
-main () {
+main() {
   local test_host=clients3.google.com
   local proxy
   local option_and_arg_provided=no
@@ -1094,7 +1115,7 @@ main () {
         exit 0
         ;;
       *)
-        echo "Unknown option: $option"
+        echo "Unknown option: ${option}"
         usage
         exit 1
         ;;
@@ -1103,6 +1124,5 @@ main () {
   fi
 }
 main "$@"
-
 
 exit "${fail_count}"
diff --git a/installer/chromeos-install b/installer/chromeos-install
--- a/installer/chromeos-install
+++ b/installer/chromeos-install
@@ -1,5 +1,5 @@
 #!/bin/sh -u
-# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
+# Copyright 2012 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 #
@@ -20,6 +20,9 @@ SRC_BLKSIZE=512
 
 # Copy the rootfs in chunks to optimize disk cache usage.
 NUM_ROOTFS_CHUNKS=4
+
+# Cached recovery key version read from flashrom.
+RECOVERY_KEY_VERSION=
 
 # Helpful constants.
 HARDWARE_DIAGNOSTICS_PATH=/tmp/hardware_diagnostics.log
@@ -63,6 +66,7 @@ DEFINE_boolean storage_diags "${FLAGS_FALSE}" "Print storage diagnostic \
 information on failure"
 DEFINE_boolean lvm_stateful "${FLAGS_FALSE}" "Create LVM-based stateful \
 partition"
+DEFINE_boolean minimal_copy "${FLAGS_FALSE}" "Minimal copy of partitions."
 
 
 # Parse command line
@@ -406,12 +410,14 @@ loop_offset_cleanup() {
 }
 
 # Mount the existing loop device at the mountpoint in $TMPMNT.
-# Args: optional 'readwrite'. If present, mount read-write, otherwise read-only.
+# Args: optional 'rw'. If present, mount read-write, otherwise read-only.
 mount_on_loop_dev() {
-  local rw_flag=${1-readonly}
-  set --
-  if [ "${rw_flag}" != "readwrite" ]; then
-    set -- "$@" -o ro
+  local rw_flag=${1-ro}
+  set -- -o nosuid,nodev
+  if [ "${rw_flag}" != "rw" ]; then
+    set -- "$@",ro,exec
+  else
+    set -- "$@",rw,noexec
   fi
   tracked_mount "$@" "${LOOP_DEV}" "${TMPMNT}"
 }
@@ -579,14 +585,14 @@ wipe_stateful() {
     local thinpool_metadata_size="$(get_thinpool_metadata_size \
       "${thinpool_size}")"
 
-    lvcreate --size "${thinpool_size}M" --poolmetadatasize \
+    lvcreate --zero n --size "${thinpool_size}M" --poolmetadatasize \
       "${thinpool_metadata_size}M" --thinpool "thinpool" "${vg_name}/thinpool"
 
     echo "Creating unencrypted volume"
     local lv_size="$(get_logical_volume_size "${DEV}")"
     lvcreate --thin -V "${lv_size}M" -n "unencrypted" "${vg_name}/thinpool"
 
-    NUM_STATEFUL_SECTORS=$(( lv_size * 2 * 1024 ))
+    NUM_STATEFUL_SECTORS=$(( lv_size * 1024 * 1024 / DST_BLKSIZE ))
     DEV="/dev/${vg_name}/unencrypted"
   fi
 
@@ -606,10 +612,14 @@ wipe_stateful() {
     ;;
   esac
 
-  # When the stateful partition is wiped the TPM ownership must be reset. This
-  # command will not work on older devices which do not support it. In that case
-  # it will be ignored.
-  crossystem clear_tpm_owner_request=1 || true
+  # When the stateful partition is wiped the TPM ownership must be reset.
+  # This command will not work on Flex devices which do not support it.
+  # In that case the result will be ignored.
+  if [ "$(crossystem mainfw_type)" != "nonchrome" ]; then
+    crossystem clear_tpm_owner_request=1
+  else
+    crossystem clear_tpm_owner_request=1 || true
+  fi
 }
 
 # Install the stateful partition content
@@ -664,7 +674,7 @@ install_stateful() {
     fi
     ;;
   esac
-  mount_on_loop_dev readwrite
+  mount_on_loop_dev rw
 
   # Move log files listed in FLAGS_lab_preserve_logs from stateful_partition to
   # a dedicated location. This flag is used to enable Autotest to collect log
@@ -707,20 +717,6 @@ install_stateful() {
   "
 
   if crossystem 'cros_debug?1'; then
-    # For a debug install, add a separate partition for developer-tools.
-    if [ "${FLAGS_lvm_stateful}" -eq "${FLAGS_TRUE}" ]; then
-      local lv_size="$(get_logical_volume_size "${dst_stateful_partition}")"
-      local stateful_fs_format="$(get_fs_format "${PARTITION_NUM_STATE}")"
-
-      lvcreate --thin -V "${lv_size}M" -n "dev-image" "${vg_name}/thinpool"
-      lvchange -ay "${vg_name}/dev-image"
-
-      mkfs "${stateful_fs_format}" ${NUM_STATEFUL_SECTORS} \
-        "/dev/${vg_name}/dev-image" "DEVTOOLS"
-      mkdir -p "${TMPMNT}/dev_image"
-      mount "/dev/${vg_name}/dev-image" "${TMPMNT}/dev_image"
-    fi
-
     dirlist="
       ${dirlist}
       var_overlay/db/pkg
@@ -734,7 +730,8 @@ install_stateful() {
        local f_path=$(dirname "${f}")
        local dlc_package=$(basename "${f_path}")
        local dlc_id=$(basename $(dirname "${f_path}"))
-       if grep '\"preload-allowed\":\s*true' "${f}"; then
+       if grep -q '\"preload-allowed\":\s*true' "${f}"; then
+         echo "Preloading DLC=${dlc_id}"
          dirlist="
            ${dirlist}
            var_overlay/cache/dlc-images/${dlc_id}/${dlc_package}
@@ -778,8 +775,11 @@ install_stateful() {
     cp -au "${ROOT}/mnt/stateful_partition/${dir}" "${TMPMNT}/${parent}"
   done
 
-  if mountpoint -q "${TMPMNT}/dev_image"; then
-    umount "${TMPMNT}/dev_image"
+  local manifest="${ROOT}/home/chronos/user/startup_manifest.json"
+  if [ -e "${manifest}" ]; then
+    local dst_dir="${TMPMNT}/unencrypted/preserve"
+    mkdir -p "${dst_dir}"
+    cp "${manifest}" "${dst_dir}"
   fi
 
   umount_from_loop_dev
@@ -793,6 +793,41 @@ install_stateful() {
     fi
     ;;
   esac
+}
+
+# Get the recovery key version.
+# Default value on failure is "1".
+get_recovery_key_version() {
+  local tmpdir="$(mktemp -d)"
+  local tmpflash="${tmpdir}/flash"
+  local tmpflashparsed="${tmpdir}/flashparsed"
+
+  # Suppress failures and fallback to default value.
+  set +e
+
+  # Read the flashrom.
+  flashrom -i GBB:"${tmpflash}" -r >&2
+  if [ "$?" -ne 0 ]; then
+    echo "Failed to read flashrom, defaulting to recovery key version=\"1\"" >&2
+    # Default.
+    echo "1"
+  else
+    # If successful, continue to extract the key version.
+    futility show "${tmpflash}" > "${tmpflashparsed}"
+    local key_version=$(grep -A3 'Recovery Key:' "${tmpflashparsed}" \
+      | grep 'Key Version:' \
+      | grep -Eo '[0-9]+')
+    echo "${key_version}"
+  fi
+
+  # Cleanup tmp files and directory.
+  for p in "${tmpflash}" "${tmpflashparsed}"; do
+    unlink "${p}"
+  done
+  rmdir "${tmpdir}"
+
+  # Back to strict.
+  set -e
 }
 
 # Copy partition from src to dst (figures out partition offsets). Note, this
@@ -851,9 +886,21 @@ copy_partition() {
       "${cache_input}"
     ;;
   "${PARTITION_NUM_MINIOS_A}"|"${PARTITION_NUM_MINIOS_B}")
-    # Always copy from MINIOS_A for MiniOS partitions.
-    part_size=$(partsize "${src}" "${PARTITION_NUM_MINIOS_A}")
-    src_offset=$(partoffset "${src}" "${PARTITION_NUM_MINIOS_A}")
+    # Choose to copy from A or B for miniOS partitions.
+    local src_part_num
+    if [ -n "${RECOVERY_KEY_VERSION}" ]; then
+      echo "Using cached recovery key version=\"${RECOVERY_KEY_VERSION}\""
+    else
+      RECOVERY_KEY_VERSION=$(get_recovery_key_version)
+      echo "Using recovery key version=\"${RECOVERY_KEY_VERSION}\""
+    fi
+    if [ "${RECOVERY_KEY_VERSION}" -eq "1" ]; then
+      src_part_num="${PARTITION_NUM_MINIOS_A}"
+    else
+      src_part_num="${PARTITION_NUM_MINIOS_B}"
+    fi
+    part_size=$(partsize "${src}" "${src_part_num}")
+    src_offset=$(partoffset "${src}" "${src_part_num}")
     write_partition "${part_num}" "${part_size}" "${dst_offset}" \
       "${src_offset}" "${src}" "${dst}" "${chunk_num}" "${total_chunks}" \
       "${cache_input}"
@@ -1021,6 +1068,13 @@ legacy_offset_size_export() {
   NUM_STATEFUL_SECTORS="$(partsize "$1" "${PARTITION_NUM_STATE}")"
 }
 
+ufs_init() {
+  local ufs_init_bin="/usr/sbin/factory_ufs"
+  if [ -x "${ufs_init_bin}" ]; then
+    ${ufs_init_bin} provision
+  fi
+}
+
 main() {
   # Be aggressive.
   set -eu
@@ -1033,7 +1087,8 @@ main() {
 
   # We untrap on success and run cleanup ourselves. Otherwise, on any failure,
   # run our custom trap method to gather any diagnostic data before cleaning up.
-  trap cleanup_on_failure EXIT
+  # Also, cleanup mounts if install is interrupted.
+  trap cleanup_on_failure INT TERM EXIT
 
   # Clean media browser mounts if they've popped up.
   prepare_disk
@@ -1060,23 +1115,11 @@ main() {
   . "${ROOT}/usr/sbin/write_gpt.sh"
   load_base_vars
 
-  # This was moved out of check_payload_image because DEFAULT_ROOTDEV
-  # is not defined until after the GPT helper functions are loaded.
-  if [ "${FLAGS_skip_src_removable}" -eq "${FLAGS_FALSE}" ]; then
-    if [ "$(cat "/sys/block/${SRC#/dev/}/removable")" != "1" ]; then
-      # Removable flag is implemented inconsistently for ARM sdcard reader.
-      # Allow all devices except the default fixed drive.
-      if [ "${SRC}" = "$(get_fixed_dst_drive)" ]; then
-        trap - EXIT
-        cleanup
-        die "Error: Source can not be the destination device: ${SRC}"
-      fi
-    fi
-  fi
-
   # Now that we have loaded the partition table we can actually read the format
   # and partition information.
   STATEFUL_FORMAT="$(get_format "${PARTITION_NUM_STATE}")"
+
+  ufs_init
 
   DST=${FLAGS_dst:-$(get_fixed_dst_drive)}
   check_dst
@@ -1151,7 +1194,13 @@ main() {
   copy_partition "${PARTITION_NUM_OEM}" "${SRC}" "${DST}" 1 1 false        # 8
   copy_partition "${PARTITION_NUM_ROOT_C}" "${SRC}" "${DST}" 1 1 false     # 7
   copy_partition "${PARTITION_NUM_KERN_C}" "${SRC}" "${DST}" 1 1 false     # 6
-  copy_partition "${PARTITION_NUM_KERN_B}" "${SRC}" "${DST}" 1 1 false     # 4
+  # Cache the first read of KERN so the second is read from RAM.
+  # This is okay as they read from the same source.
+  if [ "${FLAGS_minimal_copy}" -eq "${FLAGS_TRUE}" ]; then
+    echo "Skipping copy of B kernel partition."
+  else
+    copy_partition "${PARTITION_NUM_KERN_B}" "${SRC}" "${DST}" 1 1 true    # 4
+  fi
   copy_partition "${PARTITION_NUM_KERN_A}" "${SRC}" "${DST}" 1 1 false     # 2
 
   # We want to chunk up the root filesystem.  We do this because we're
@@ -1162,8 +1211,12 @@ main() {
   # prevents this.
   local chunk_num
   for chunk_num in $(seq "${NUM_ROOTFS_CHUNKS}"); do
-    copy_partition "${PARTITION_NUM_ROOT_B}" "${SRC}" "${DST}" \
-       "${chunk_num}" "${NUM_ROOTFS_CHUNKS}" true                          # 5
+    if [ "${FLAGS_minimal_copy}" -eq "${FLAGS_TRUE}" ]; then
+      echo "Skipping copy of B root partition."
+    else
+      copy_partition "${PARTITION_NUM_ROOT_B}" "${SRC}" "${DST}" \
+         "${chunk_num}" "${NUM_ROOTFS_CHUNKS}" true                        # 5
+    fi
     copy_partition "${PARTITION_NUM_ROOT_A}" "${SRC}" "${DST}" \
        "${chunk_num}" "${NUM_ROOTFS_CHUNKS}" false                         # 3
   done
@@ -1174,9 +1227,14 @@ main() {
   # We want the MINIOS partitions be last just in case writing to other
   # partitions fail at some point, we don't lose the ability to do recovery.
   if [ -n "${PARTITION_NUM_MINIOS_A}" ]; then
-    copy_partition "${PARTITION_NUM_MINIOS_A}" "${SRC}" "${DST}" 1 1 false # 9
+    # Cache the first read of MINIOS so the second is read from RAM.
+    # This is okay as they read from the same source.
+    copy_partition "${PARTITION_NUM_MINIOS_A}" "${SRC}" "${DST}" 1 1 true  # 9
   fi
-  if [ -n "${PARTITION_NUM_MINIOS_B}" ]; then
+
+  if [ "${FLAGS_minimal_copy}" -eq "${FLAGS_TRUE}" ]; then
+    echo "Skipping copy of B miniOS partition."
+  elif [ -n "${PARTITION_NUM_MINIOS_B}" ]; then
     copy_partition "${PARTITION_NUM_MINIOS_B}" "${SRC}" "${DST}" 1 1 false # 10
   fi
 
diff --git a/power_manager/powerd/powerd_suspend b/power_manager/powerd/powerd_suspend
--- a/power_manager/powerd/powerd_suspend
+++ b/power_manager/powerd/powerd_suspend
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
+# Copyright 2010 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
@@ -96,10 +96,6 @@ log_suspend_stats() {
   rm "${tempfile}"
 }
 
-is_kip() {
-  crossystem hwid | grep -q '^KIP '
-}
-
 igb_devices=""
 
 # The Intel gigabit driver (igb) prevents Intel platforms (the only platforms
@@ -107,7 +103,7 @@ igb_devices=""
 # (see b/189345571). So in order to enter S0ix, need to unbind its devices while
 # suspending, and rebind again at resume.
 unbind_igb_devices() {
-  /sbin/lsmod | grep -qw "^igb"
+  lsmod | grep -qw "^igb"
   if [ $? -ne 0 ]; then
     return
   fi
@@ -130,11 +126,6 @@ bind_igb_devices() {
     log_msg "Re-binding igb driver to ${pcidev} after resume"
     echo "${pcidev}" > /sys/bus/pci/drivers/igb/bind
   done
-}
-
-# Checks if the system has a Huawei Technologies Mobile Broadband Module.
-has_huawei_modem() {
-  lsusb -d 12d1:15bb
 }
 
 # Powers "on" or "off" the built-in modem via EC.
@@ -275,9 +266,14 @@ eval set -- "${FLAGS_ARGV}"
 # (http://crbug.com/338015).
 metrics_client -e Power.SuspendAttempt 0 2 &
 
-# Log the time before going to suspend (no-op if no RTC).
-cp /sys/class/rtc/rtc0/since_epoch "${SUSPEND_TO_RAM_TIME_FILE}" \
-  2> /dev/null || true
+# Don't log the suspend time when hibernating, otherwise the
+# Power.TimeInSuspendAtResume metric would include hibernations,
+# which would be misleading.
+if [ "${FLAGS_suspend_to_disk}" -eq "${FLAGS_FALSE}" ]; then
+  # Log the time before going to suspend (no-op if no RTC).
+  cp /sys/class/rtc/rtc0/since_epoch "${SUSPEND_TO_RAM_TIME_FILE}" \
+    2> /dev/null || true
+fi
 
 # Remove last_resume_timings to ensure the file is fresh on resume.
 rm -f "${LAST_RESUME_TIMINGS_FILE}"
@@ -289,13 +285,6 @@ if [ $? -eq 0 ]; then
   echo OnBattery > "${POWER_STATUS_ON_SUSPEND_FILE}"
 else
   echo OnAC > "${POWER_STATUS_ON_SUSPEND_FILE}"
-fi
-
-# Is this a Kip system with Huawei modem?
-kip_with_huawei_modem=0
-if is_kip && has_huawei_modem; then
-  log_msg "Kip with Huawei modem"
-  kip_with_huawei_modem=1
 fi
 
 result="${RESULT_FAILURE}"
@@ -319,9 +308,6 @@ else
   if [ -x "/usr/sbin/modem_shutdown" ]; then
     /usr/sbin/modem_shutdown
   fi
-  if [ "${kip_with_huawei_modem}" -eq 1 ]; then
-    ec_power_modem off
-  fi
 
   # Compact memory if it is fragmented.
   try_compact_memory
@@ -337,20 +323,27 @@ else
     /sbin/hwclock -V > /dev/null
   fi
 
-  # Echo freeze to /sys/power/state on platforms that support suspend to idle.
-  # Echo disk to enter hibernate/S4.
-  action='mem'
+  # For hibernate, invoke the hiberman helper process to take us all the way
+  # down.
   if [ "${FLAGS_suspend_to_disk}" -eq 0 ]; then
-    action='disk'
-  elif [ "${FLAGS_suspend_to_idle}" -eq 0 ]; then
-    action='freeze'
-    unbind_igb_devices
+    error="Failed to hibernate"
+    /sbin/minijail0 --config=/usr/share/minijail/hiberman.conf \
+        -- /usr/sbin/hiberman hibernate
+
+  else
+    # Echo freeze to /sys/power/state on platforms that support suspend to idle.
+    action='mem'
+    if [ "${FLAGS_suspend_to_idle}" -eq 0 ]; then
+      action='freeze'
+      unbind_igb_devices
+    fi
+
+    # Suspend. This is piped through cat since we want to determine
+    # the causes of failures -- dash's "echo" command appears to not print
+    # anything in response to write errors.
+    error=$( (printf '%s' "${action}" | cat > /sys/power/state) 2>&1)
   fi
 
-  # Suspend. This is piped through cat since we want to determine
-  # the causes of failures -- dash's "echo" command appears to not print
-  # anything in response to write errors.
-  error=$( (printf '%s' "${action}" | cat > /sys/power/state) 2>&1)
   if [ $? -eq 0 ]; then
     # On resume:
     result="${RESULT_SUCCESS}"
@@ -407,10 +400,6 @@ else
 
   bind_igb_devices
 
-  # Power back on modems if they were powered off before suspend.
-  if [ "${kip_with_huawei_modem}" -eq 1 ]; then
-    ec_power_modem on
-  fi
   # `modem_startup` (along with `modem_shutdown`) exists only if board-specific
   # overlays provide one. Future project should re-use the script name when
   # powering back on modems after suspending is required.
@@ -424,7 +413,7 @@ fi
 
 send_uma_result "${result}"
 
-# Refresh mosys eventlog to help feedback reports pick up the latest snapshot.
+# Refresh eventlog to help feedback reports pick up the latest snapshot.
 /usr/share/userfeedback/scripts/eventlog &
 
 log_msg "Resume finished"
diff --git a/vm_tools/upgrade_container/upgrade_container b/vm_tools/upgrade_container/upgrade_container
--- a/vm_tools/upgrade_container/upgrade_container
+++ b/vm_tools/upgrade_container/upgrade_container
@@ -1,5 +1,5 @@
-#!/bin/sh
-# Copyright 2019 The Chromium OS Authors. All rights reserved.
+#!/bin/bash
+# Copyright 2023 The ChromiumOS Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
@@ -22,11 +22,15 @@
 set -ex
 
 to_buster() {
-  [ $1 = 'DEBIAN_BUSTER' ]
+  [ "$1" = 'DEBIAN_BUSTER' ]
 }
 
 to_bullseye() {
-  [ $1 = 'DEBIAN_BULLSEYE' ]
+  [ "$1" = 'DEBIAN_BULLSEYE' ]
+}
+
+to_bookworm() {
+  [ "$1" = 'DEBIAN_BOOKWORM' ]
 }
 
 # Really old versions of openssl will prioritize expired trust chains over valid
@@ -59,18 +63,28 @@ do_upgrade() {
   # When conflicting configuration files exist between the local system and the
   # upstream package, prefer the default option. If there is no default option,
   # default to keeping the local version. This is required along with setting
-  # DEBIAN_FRONTEND above for a truly noninteractive upgrade experience.
-  APT_OPTIONS="-o Dpkg::Options::=--force-confdef
-   -o Dpkg::Options::=--force-confold"
+  # DEBIAN_FRONTEND above and passing -y --allow-releaseinfo-change for apt to
+  # hopefully really be noninteractive.
+  APT_OPTIONS=(
+   -o Dpkg::Options::=--force-confdef
+   -o Dpkg::Options::=--force-confold
+  )
 
   # If a previous run of this script was killed, it might have left packages in
   # a half-configured state. Complete the configurations.
   dpkg --configure -a || true
 
   # Upgrade everything.
-  apt-get ${APT_OPTIONS} update -y
-  apt-get ${APT_OPTIONS} upgrade -y
-  apt-get ${APT_OPTIONS} dist-upgrade -y
+  # --allow-releaseinfo-change was only added in buster, so if it fails try
+  # again without the argument in case we're on stretch.  We try this way
+  # instead of checking lsb-release or similar in case a failed upgrade leaves
+  # them with modified release info but old apt. They'll probably hit other
+  # issues if that's the case, but might as well try.
+  if ! apt-get "${APT_OPTIONS[@]}" update -y --allow-releaseinfo-change; then
+    apt-get "${APT_OPTIONS[@]}" update -y
+  fi
+  apt-get "${APT_OPTIONS[@]}" upgrade -y
+  apt-get "${APT_OPTIONS[@]}" dist-upgrade -y
 }
 
 # Debian doesn't support skip-version upgrades, so we need to make sure we're
@@ -78,7 +92,7 @@ do_upgrade() {
 # the case where we restart an upgrade after /etc/os-release has been updated.
 do_upgrade
 
-for version in $@; do
+for version in "$@"; do
   if to_buster "${version}"; then
     # No longer need to backport GPU support packages.
     rm -f /etc/apt/sources.list.d/cros-gpu.list \
@@ -95,8 +109,16 @@ for version in $@; do
 
     # The bullseye security repo is called "bullseye-security", while buster
     # uses "buster/updates"
-    sed -i 's/debian-security bullseye\/updates/debian-security bullseye-security/g' \
+    sed -i 's/debian-security\/\? bullseye\/updates/debian-security bullseye-security/g' \
       /etc/apt/sources.list
+
+  elif to_bookworm "${version}"; then
+    # Drop backports, not used yet in Crostini bookworm.
+    sed -i '/bullseye-backports/d' /etc/apt/sources.list.d/cros.list
+
+    # The actual flip to bookworm.
+    sed -i 's/bullseye/bookworm/g' /etc/apt/sources.list \
+      /etc/apt/sources.list.d/cros.list
   fi
 
   # Upgrade again, now to the new version.
